version: '3'

services:
    nginx:
        image: nginx:alpine
        ports:
            - ${NGINX_HTTP_PORT:-80}:80
        volumes:
            - "../etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "../project:/var/www/html"
        links:
            - fpm
    cli:
        build: "./cli/"
        stdin_open: true
        tty: true
        volumes:
            - "../etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "../project:/var/www/html"
    fpm:
        build: "./fpm/"
        volumes:
            - "../etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "../project:/var/www/html"
        expose:
            - 9000
    composer:
        build: "./composer/"
        volumes:
            - "../project:/var/www/html"
    db:
        build: "./mysql/"
        user: mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        expose:
            - 3306
        ports:
            - ${MYSQL_PORT_BIND:-127.0.0.1:13306}:3306
        volumes:
            - "db-data:/var/lib/mysql"

volumes:
    db-data: